build: 	pll_led_tb.v pll_led.v divider_synth.v ../../../../freq_gen.v ../../../../plle2_base.v ../../../../period_check.v ../../../../period_count.v ../../../../phase_shift.v
	- iverilog pll_led_tb.v pll_led.v divider_synth.v ../../../../freq_gen.v ../../../../plle2_base.v ../../../../period_check.v ../../../../period_count.v ../../../../phase_shift.v -o pll_led_tb
	- vvp pll_led_tb
