VERILOG_SOURCES=../freq_gen.v
# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file:
TOPLEVEL=freq_gen
# MODULE is the name of the Python test file:
MODULE=coco_test_freq_gen
TOPLEVEL_LANG=verilog

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
